In [1]:
import pandas as pd

## Advanced Manufacturing Series NIST AMS 100‐69 dataset
- Origin: https://data.nist.gov/od/id/mds2-3761

In [ ]:
from pathlib import Path
import pandas as pd

sample_path = Path("AMS_NIST/part01/L0001.csv")

df = pd.read_csv(sample_path)
df.head()

,1,77500,-6,16,100,900,-5.9145,15.87,-0.28901,914.31,...,NaN.11,NaN.12,NaN.13,NaN.14,NaN.15,NaN.16,NaN.17,NaN.18,NaN.19,NaN.20
0,1,77600.0,-5.91,16.0,100,900.0,-5.8381,15.876,94.706,1017.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,77700.0,-5.82,16.0,100,900.0,-5.7522,15.841,95.458,3615.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,77800.0,-5.73,16.0,100,900.0,-5.6652,15.855,94.620,2591.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,77900.0,-5.64,16.0,100,900.0,-5.5675,15.840,94.481,1032.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,78000.0,-5.55,16.0,100,900.0,-5.4837,15.841,94.739,1111.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Dataset columns

Each CSV file represents one layer of one printed part.

Each row corresponds to one registered measurement point during the LPBF process.
The dataset contains 40 columns but the CSV files do not contain a header.

The columns can be divided into four groups:

1. Process and machine data — columns 1–10
2. Melt Pool Monitoring (MPM) features — columns 11–19
3. Layerwise Imaging (LWI) features — columns 20–37
4. X-ray Computed Tomography (XCT) features — columns 38–40

---

### 1. Process and machine data

| # | Suggested column name | Unit | Description |
|---|---|---|---|
| 1 | `part_number` | — | Identifier of the printed part. The number corresponds to the scanning order of the four parts. |
| 2 | `build_time_us` | µs | Time during the build, synchronized with the machine clock. |
| 3 | `command_x_mm` | mm | Commanded X position of the laser, extracted from the XYPT scan command. |
| 4 | `command_y_mm` | mm | Commanded Y position of the laser, extracted from the XYPT scan command. |
| 5 | `command_laser_power_w` | W | Laser power requested by the machine control program. |
| 6 | `command_scan_speed_mm_s` | mm/s | Commanded laser scanning speed, calculated from consecutive commanded laser positions. |
| 7 | `real_x_mm` | mm | Actual measured X position of the laser, obtained from the DAQ system. |
| 8 | `real_y_mm` | mm | Actual measured Y position of the laser, obtained from the DAQ system. |
| 9 | `real_laser_power_w` | W | Actual measured laser power obtained from the DAQ system. |
| 10 | `real_scan_speed_mm_s` | mm/s | Actual scanning speed calculated from consecutive measured laser positions. |

The distinction between **command** and **real** values is important:

- `command_*` describes what the machine was instructed to do.
- `real_*` describes what the machine actually did.

This allows deviations such as laser-power drops or positioning/speed errors to be detected.

---

### 2. Melt Pool Monitoring (MPM) features

The melt pool is the small region of metal that is molten while the laser scans the powder.

NIST extracts the melt-pool shape from coaxial high-speed camera images using three image-intensity thresholds: **80, 100 and 120**.

Higher thresholds correspond to hotter/brighter regions of the observed melt pool.

| # | Suggested column name | Unit | Description |
|---|---|---|---|
| 11 | `melt_pool_length_t80_mm` | mm | Melt-pool length using intensity threshold 80. Defined as the major axis of an ellipse fitted to the detected melt-pool region. |
| 12 | `melt_pool_width_t80_mm` | mm | Melt-pool width using threshold 80. Defined as the minor axis of the fitted ellipse. |
| 13 | `melt_pool_area_t80_mm2` | mm² | Area of the detected melt pool using threshold 80. |
| 14 | `melt_pool_length_t100_mm` | mm | Melt-pool length using intensity threshold 100. |
| 15 | `melt_pool_width_t100_mm` | mm | Melt-pool width using threshold 100. |
| 16 | `melt_pool_area_t100_mm2` | mm² | Area of the detected melt pool using threshold 100. |
| 17 | `melt_pool_length_t120_mm` | mm | Melt-pool length using intensity threshold 120. |
| 18 | `melt_pool_width_t120_mm` | mm | Melt-pool width using threshold 120. |
| 19 | `melt_pool_area_t120_mm2` | mm² | Area of the detected melt pool using threshold 120. |

Approximate calibrated temperatures associated with these thresholds are:

- Threshold 80 ≈ 1800 °C
- Threshold 100 ≈ 1850 °C
- Threshold 120 ≈ 1900 °C

These values represent optical measurements and should not be interpreted as exact physical melt-pool temperatures.

---

### 3. Layerwise Imaging (LWI) features

Layerwise images are photographs of the build surface.

Images were taken under three different illumination positions:

- LED A
- LED B
- LED C

Two types of images are available:

- **Powder view after spreading** — surface after a new powder layer has been deposited, before laser scanning.
- **Exposure view after scan** — surface after the laser has scanned the layer.

For every image, NIST provides:

- the original pixel intensity;
- a 3×3 mean-filtered intensity;
- a 5×5 mean-filtered intensity.

#### Powder layer before laser exposure

| # | Suggested column name | Unit | Description |
|---|---|---|---|
| 20 | `lwi_powder_led_a_raw` | — | Original LWI pixel intensity after powder spreading, illuminated with LED A. |
| 21 | `lwi_powder_led_a_mean3` | — | Same LED A powder image after applying a 3×3 mean filter. |
| 22 | `lwi_powder_led_a_mean5` | — | Same LED A powder image after applying a 5×5 mean filter. |
| 23 | `lwi_powder_led_b_raw` | — | Original LWI pixel intensity after powder spreading, illuminated with LED B. |
| 24 | `lwi_powder_led_b_mean3` | — | Same LED B powder image after applying a 3×3 mean filter. |
| 25 | `lwi_powder_led_b_mean5` | — | Same LED B powder image after applying a 5×5 mean filter. |
| 26 | `lwi_powder_led_c_raw` | — | Original LWI pixel intensity after powder spreading, illuminated with LED C. |
| 27 | `lwi_powder_led_c_mean3` | — | Same LED C powder image after applying a 3×3 mean filter. |
| 28 | `lwi_powder_led_c_mean5` | — | Same LED C powder image after applying a 5×5 mean filter. |

#### Surface after laser exposure

| # | Suggested column name | Unit | Description |
|---|---|---|---|
| 29 | `lwi_exposure_led_a_raw` | — | Original LWI pixel intensity after the laser has scanned the layer, illuminated with LED A. |
| 30 | `lwi_exposure_led_a_mean3` | — | Same LED A exposure image after applying a 3×3 mean filter. |
| 31 | `lwi_exposure_led_a_mean5` | — | Same LED A exposure image after applying a 5×5 mean filter. |
| 32 | `lwi_exposure_led_b_raw` | — | Original LWI pixel intensity after laser scanning, illuminated with LED B. |
| 33 | `lwi_exposure_led_b_mean3` | — | Same LED B exposure image after applying a 3×3 mean filter. |
| 34 | `lwi_exposure_led_b_mean5` | — | Same LED B exposure image after applying a 5×5 mean filter. |
| 35 | `lwi_exposure_led_c_raw` | — | Original LWI pixel intensity after laser scanning, illuminated with LED C. |
| 36 | `lwi_exposure_led_c_mean3` | — | Same LED C exposure image after applying a 3×3 mean filter. |
| 37 | `lwi_exposure_led_c_mean5` | — | Same LED C exposure image after applying a 5×5 mean filter. |

The mean-filtered versions reduce local image noise and make the registered values less sensitive to small spatial alignment errors.

---

### 4. X-ray Computed Tomography (XCT) features

XCT measurements were performed **after the parts had been printed**.

Unlike the previous measurements, XCT is therefore **ex-situ** data.

The XCT volume was spatially registered with the coordinates used during the printing process.

| # | Suggested column name | Unit | Description |
|---|---|---|---|
| 38 | `xct_voxel_raw` | — | Original XCT voxel intensity corresponding to this spatial location in the finished part. |
| 39 | `xct_voxel_mean3` | — | XCT value after applying a 3×3×3 mean filter around the voxel. |
| 40 | `xct_voxel_mean5` | — | XCT value after applying a 5×5×5 mean filter around the voxel. |

The XCT features provide information about the final internal structure of the printed part and allow in-situ process behaviour to be compared with the resulting part structure.

In [31]:
columns = [
    "part_number",
    "build_time_us",
    "command_x_mm",
    "command_y_mm",
    "command_laser_power_w",
    "command_scan_speed_mm_s",
    "real_x_mm",
    "real_y_mm",
    "real_laser_power_w",
    "real_scan_speed_mm_s",
    "melt_pool_length_t80_mm",
    "melt_pool_width_t80_mm",
    "melt_pool_area_t80_mm2",
    "melt_pool_length_t100_mm",
    "melt_pool_width_t100_mm",
    "melt_pool_area_t100_mm2",
    "melt_pool_length_t120_mm",
    "melt_pool_width_t120_mm",
    "melt_pool_area_t120_mm2",
    "lwi_powder_led_a_raw",
    "lwi_powder_led_a_mean3",
    "lwi_powder_led_a_mean5",
    "lwi_powder_led_b_raw",
    "lwi_powder_led_b_mean3",
    "lwi_powder_led_b_mean5",
    "lwi_powder_led_c_raw",
    "lwi_powder_led_c_mean3",
    "lwi_powder_led_c_mean5",
    "lwi_exposure_led_a_raw",
    "lwi_exposure_led_a_mean3",
    "lwi_exposure_led_a_mean5",
    "lwi_exposure_led_b_raw",
    "lwi_exposure_led_b_mean3",
    "lwi_exposure_led_b_mean5",
    "lwi_exposure_led_c_raw",
    "lwi_exposure_led_c_mean3",
    "lwi_exposure_led_c_mean5",
    "xct_voxel_raw",
    "xct_voxel_mean3",
    "xct_voxel_mean5",
]

df = pd.read_csv(sample_path, names=columns, header=0)
df.head()

,part_number,build_time_us,command_x_mm,command_y_mm,command_laser_power_w,command_scan_speed_mm_s,real_x_mm,real_y_mm,real_laser_power_w,real_scan_speed_mm_s,...,lwi_exposure_led_a_mean5,lwi_exposure_led_b_raw,lwi_exposure_led_b_mean3,lwi_exposure_led_b_mean5,lwi_exposure_led_c_raw,lwi_exposure_led_c_mean3,lwi_exposure_led_c_mean5,xct_voxel_raw,xct_voxel_mean3,xct_voxel_mean5
0,1,77600.0,-5.91,16.0,100,900.0,-5.8381,15.876,94.706,1017.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,77700.0,-5.82,16.0,100,900.0,-5.7522,15.841,95.458,3615.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,77800.0,-5.73,16.0,100,900.0,-5.6652,15.855,94.620,2591.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,77900.0,-5.64,16.0,100,900.0,-5.5675,15.840,94.481,1032.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,78000.0,-5.55,16.0,100,900.0,-5.4837,15.841,94.739,1111.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
df.isna().all()

part_number                 False
build_time_us               False
command_x_mm                False
command_y_mm                False
command_laser_power_w       False
command_scan_speed_mm_s     False
real_x_mm                   False
real_y_mm                   False
real_laser_power_w          False
real_scan_speed_mm_s        False
melt_pool_length_t80_mm     False
melt_pool_width_t80_mm      False
melt_pool_area_t80_mm2      False
melt_pool_length_t100_mm    False
melt_pool_width_t100_mm     False
melt_pool_area_t100_mm2     False
melt_pool_length_t120_mm    False
melt_pool_width_t120_mm     False
melt_pool_area_t120_mm2     False
lwi_powder_led_a_raw         True
lwi_powder_led_a_mean3       True
lwi_powder_led_a_mean5       True
lwi_powder_led_b_raw         True
lwi_powder_led_b_mean3       True
lwi_powder_led_b_mean5       True
lwi_powder_led_c_raw         True
lwi_powder_led_c_mean3       True
lwi_powder_led_c_mean5       True
lwi_exposure_led_a_raw       True
lwi_exposure_led_a_mean3     True
lwi_exposure_led_a_mean5     True
lwi_exposure_led_b_raw       True
lwi_exposure_led_b_mean3     True
lwi_exposure_led_b_mean5     True
lwi_exposure_led_c_raw       True
lwi_exposure_led_c_mean3     True
lwi_exposure_led_c_mean5     True
xct_voxel_raw                True
xct_voxel_mean3              True
xct_voxel_mean5              True
dtype: bool

## AM Bench 2022 — LPBF 3D Builds of IN718 (AMB2022-01)

- **Thermography dataset:** https://doi.org/10.18434/mds2-2715
- **Raw thermal signal:** `*_Signal.h5`
- **Temperature data:** `*_Te05.h5`
- **Time Above Melt:** `*_TAM.h5`
- **Solid Cooling Rate:** `*_SCR.h5`

- **Laser scan strategy dataset:** https://doi.org/10.18434/mds2-2607
- **Laser movement / control data:** `AMB2022-01-AMMT-XYPT_v1.h5`
  - `X` — commanded X position
  - `Y` — commanded Y position
  - `P` — commanded laser power
  - `T` — trigger / synchronization signal

## NIST AMMT — Overhang Part X4

- **Dataset:** https://doi.org/10.18434/M32233
- **NIST page:** https://data.nist.gov/pdr/lps/ark:/88434/mds2-2233

### Files

- **`Build Metadata.zip`** — build/material/laser metadata. Useful mainly as context and calibration information.
- **`DAQ.zip`** — actual measured machine data: laser position and laser power, sampled every 10 µs. **Highly useful.**
- **`Layer Camera Metadata.zip`** — calibration data for the layer camera. Useful only if processing layer images.
- **`LayerCamera_PNGs.zip`** — layer images before/after laser exposure under different illumination. Low priority for L3.
- **`LayerCameraAfterSpreading.tif`** — layer-camera images after powder spreading. Low priority.
- **`LayerCameraBurned.tif`** — layer-camera images after laser exposure. Low priority.
- **`Melt Pool Camera AVIs Lagarith.zip`** — raw high-speed melt-pool camera videos, one video per layer. Useful for L2/CV, but not directly for L3.
- **`Melt Pool Camera Metadata.zip`** — melt-pool camera calibration metadata. Needed only if processing raw melt-pool images.
- **`Melt Pool Camera TIFF Stacks.zip`** — same melt-pool frames in TIFF-stack format. Alternative to AVI; no need to use both.
- **`Part Geometry.zip`** — CAD/STL geometry of the printed part. Context only.
- **`XYPT Commands.zip`** — commanded laser `X`, `Y`, `Power`, `Trigger`, sampled every 10 µs. **Highly useful.**